# Generated by Django 4.0.2 on 2022-03-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinationCountry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('city', 'CITY'), ('state', 'STATE')], default='', max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('tlPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('countryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.country')),
            ],
        ),
        migrations.CreateModel(
            name='CityLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('city', 'CITY'), ('locality', 'LOCALITY')], default='', max_length=200, null=True)),
                ('cityLocality', models.CharField(blank=True, max_length=200, null=True)),
                ('clPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('countryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.typelocation')),
            ],
        ),
    ]
