# Generated by Django 4.0.2 on 2022-03-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinationCountry', '0002_typelocation_citylocality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylocality',
            old_name='cityLocality',
            new_name='cityLocation',
        ),
        migrations.CreateModel(
            name='LocationLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('llPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('cityLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.citylocality')),
                ('countryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.country')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationCountry.typelocation')),
            ],
        ),
    ]
