# Generated by Django 4.0.2 on 2022-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationCountry', '0003_rename_citylocality_citylocality_citylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocality',
            name='cityLocation',
            field=models.CharField(max_length=200),
        ),
    ]
